
from django.urls import path

from voteApp import views

urlpatterns = [
    path('',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('loginverify',views.loginverify,name='loginverify'),
    path('addstudent',views.addstudent,name='addstudent'),
    path('addnewstudent',views.addnewstudent,name='addnewstudent'),
    path('managecourse',views.managecourse,name='managecourse'),
    path('homeadmin',views.homeadmin,name='homeadmin'),
    path('addcourse',views.addcourse,name='addcourse'),
    path('addnewcourse',views.addnewcourse,name='addnewcourse'),
    path('addnew',views.addnew,name='addnew'),
    path('complaint',views.complaint,name='complaint'),
    path('electioncod',views.electioncod,name='electioncod'),
    path('electiondate',views.electiondate,name='electiondate'),
    path('searchdate',views.searchdate,name='searchdate'),
    path('searchstudent',views.searchstudent,name='searchstudent'),
    path('searchviewnom',views.searchviewnom,name='searchviewnom'),
    path('searchmanageele',views.searchmanageele,name='searchmanageele'),
    path('searchcomplaint',views.searchcomplaint,name='searchcomplaint'),
    path('manageele',views.manageele,name='manageele'),
    path('reply/<int:id>',views.reply,name='reply'),
    path('result',views.result,name='result'),
    path('student',views.student,name='student'),
    path('viewnom',views.viewnom,name='viewnom'),
    path('elcodhome',views.elcodhome,name='elcodhome'),
    path('viewnomec',views.viewnomec,name='viewnomec'),
    path('searchcourse',views.searchcourse,name='searchcourse'),
    path('votres',views.votres,name='votres'),
    path('newelectiondate',views.newelectiondate,name='newelectiondate'),
    path('newelection',views.newelection,name='newelection'),
    path('addnewelectioncoo',views.addnewelectioncoo,name='addnewelectioncoo'),
    path('deletestudent/<int:id>',views.deletestudent,name='deletestudent'),
    path('deletecourse/<int:id>',views.deletecourse,name='deletecourse'),
    path('deleteelectiondate/<int:id>',views.deleteelectiondate,name='deleteelectiondate'),
    path('deleteelcod/<int:id>',views.deleteelcod,name='deleteelcod'),
    path('addeditstudent/<int:id>',views.addeditstudent,name='addeditstudent'),
    path('addeditstudentadd',views.addeditstudentadd,name='addeditstudentadd'),
    path('editelectiondate/<int:id>',views.editelectiondate,name='editelectiondate'),
    path('addeditelectiondate',views.addeditelectiondate,name='addeditelectiondate'),
    path('editelectioncood/<int:id>',views.editelectioncood,name='editelectioncood'),
    path('addeditelectioncood',views.addeditelectioncood,name='addeditelectioncood'),
    path('sendingreply',views.sendingreply,name='sendingreply'),
    path('viewpost',views.viewpost,name='viewpost'),
    path('viewresult/<int:id>',views.viewresult,name='viewresult'),
    path('electioncoodviewresult/<int:id>',views.electioncoodviewresult,name='electioncoodviewresult'),
    path('viewnominee',views.viewnominee,name='viewnominee'),
    path('viewfeedback',views.viewfeedback,name='viewfeedback'),

    path('electipndat',views.electipndat,name='electipndat'),
    path('viewnomineeonly',views.viewnomineeonly,name='viewnomineeonly'),

    path('reply_app',views.reply_app,name='reply_app'),
    path('sendnomination',views.sendnomination,name='sendnomination'),
    path('send_complaint_app',views.send_complaint_app,name='send_complaint_app'),
    path('registration',views.registration,name='registration'),
    path('login_code',views.login_code,name='login_code'),
    path('resultt',views.resultt,name='resultt'),
    path('vote',views.vote,name='vote'),
    path('accept/<int:id>',views.accept,name='accept'),
    path('reject/<int:id>',views.reject,name='reject'),
    path('viewelectiondate',views.viewelectiondate,name='viewelectiondate'),
    path('forgot_password',views.forgot_password,name='forgot_password'),
    path('/face_verification_fn',views.face_verification_fn,name='face_verification_fn'),
    path('/cryptophotoupload',views.cryptophotoupload,name='cryptophotoupload'),
    path('cryptophotoupload',views.cryptophotoupload,name='cryptophotoupload'),
    path('viewfeedbackk',views.viewfeedbackk,name='viewfeedbackk'),
    path('sendnotification',views.sendnotification,name='sendnotification'),
    path('send_feedback_app',views.send_feedback_app,name='send_feedback_app'),
    path('viewnotificationmmm',views.viewnotificationmmm,name='viewnotificationmmm'),
    path('sendnotifications',views.sendnotifications,name='sendnotifications'),

]
